"""Agent execution loop and command-line chat interface.

Coordinates persistent message storage, context assembly, and LLM reasoning.
"""

import sys
import uuid
from agent.context import build_context
from agent.llm import LLMError, call_llm
from memory.interface import save_message


def run_agent(
    user_message: str,
    session_id: str,
) -> str:
    """Execute a single turn of the agent lifecycle.

    Execution flow:
    1. Persist the incoming user message.
    2. Assemble the full context (system instruction, memories, recent turns, user prompt).
    3. Invoke the LLM with the assembled context.
    4. Persist the generated assistant response.
    5. Return the assistant response.

    Parameters
    ----------
    user_message : str
        The latest prompt or question from the user.
    session_id : str
        The unique session identifier.

    Returns
    -------
    str
        The response generated by the agent.
    """
    # 1. Save the user message
    save_message(
        session_id=session_id,
        role="user",
        content=user_message,
    )

    # 2. Build the context
    context = build_context(
        user_message=user_message,
        session_id=session_id,
    )

    # 3. Call the LLM
    assistant_response = call_llm(context)

    # 4. Save the assistant response
    save_message(
        session_id=session_id,
        role="assistant",
        content=assistant_response,
    )

    # 5. Return the assistant response
    return assistant_response


def cli() -> None:
    """Run an interactive CLI chat session with the agent."""
    print("=" * 60)
    print("  Agentic Long-Horizon Memory - Interactive CLI")
    print("=" * 60)
    print("Type 'exit' or 'quit' to terminate the session.\n")

    default_session = f"session_{uuid.uuid4().hex[:8]}"
    try:
        session_input = input(f"Enter session ID [default: {default_session}]: ").strip()
        session_id = session_input if session_input else default_session
    except (KeyboardInterrupt, EOFError):
        print("\nSession aborted.")
        sys.exit(0)

    print(f"\nActive Session: {session_id}")
    print("-" * 60)

    while True:
        try:
            user_input = input("\nUser: ").strip()

            if not user_input:
                print("Please enter a non-empty message.")
                continue

            if user_input.lower() in ("exit", "quit"):
                print("\nEnding session. Goodbye!")
                break

            response = run_agent(user_message=user_input, session_id=session_id)
            print(f"\nAgent: {response}")

        except KeyboardInterrupt:
            print("\n\nSession interrupted by user. Goodbye!")
            break
        except LLMError as err:
            print(f"\n[Agent Error]: {err}")
        except Exception as err:
            # Safe generic error message without exposing credentials or internal traces
            print(f"\n[System Error]: An unexpected error occurred ({type(err).__name__}).")


if __name__ == "__main__":
    cli()
